apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # echo -n estoEsMiSecretJWT | base64
  JWT_SECRET: ZXN0b0VzTWlTZWNyZXRKV1Q=
  # EstoEsUnPassWordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=