apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # echo -n superman@google.com | base64
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # EstoEsUnPassWordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=